---
driver: docker
driver_config:
  privileged: true

platforms:
- name: centos-6.5
  driver_config:
    image: baseline-a
    platform: centos

suites:
- name: default
  run_list:
  - recipe[cookbook-b]
  attributes: {}
